services:
  # Backend Service
  - type: web
    name: blog-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  # Frontend Service  
  - type: web
    name: blog-frontend
    env: static
    plan: free
    buildCommand: cd clients && npm install && npm run build
    staticPublishPath: clients/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
