services:
  # Backend Service
  - type: web
    name: blog-website-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  # Frontend Service  
  - type: web
    name: blog-website-frontend
    env: static
    plan: free
    rootDir: clients
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
